### ISSUE TITLE
Upgrade hot-shots?

### ISSUE THREAD

**Issue by EyePulp** [zefferus/dogear#2]
Howdy;
We're using dogear v2.0.3 and v3.0.0 on separate projects.  Would you consider bumping to the current version of hot-shots (v5.5.1) for both 2.x and 3.x versions?  There are some improvements to the statsd client we'd like to take advantage of.  Thanks!

**Comment by PizzaBrandon** [comment]
I'm glad you find the plugin useful. PRs are welcome!

**Comment by EyePulp** [comment]
I'm not sure how to create a PR to update the v2.x version.  In this case we branched from your v2.0.3 tag, and made the changes on that branch to avoid interfering with master.  That way you can still npm publish for v2 and v3 separately.

However I can't do a PR from our v2.x without interfering with master.  Is there a way you'd prefer us to make the changes?

**Comment by PizzaBrandon** [comment]
I just created a `v2` branch based on v2.0.3 tag. You can PR against that branch separately from `master`. Is it just a version bump or are there breaking changes that need to be accounted for?

**Comment by PizzaBrandon** [comment]
I see now. `v2` points to `hot-shots` v4. The latest of `dogear` points to ^5, so it should pick up 5.5.1 for free and shouldn't need a change.

**Comment by EyePulp** [comment]
Just a version bump for hot-shots and npm.  No other changes needed.  You still want our PR for v2 or do you want to make the change?

**Comment by PizzaBrandon** [comment]
Published as 2.0.4. Thanks!

**Comment by EyePulp** [comment]
Awesome - thanks for taking care of it, and thanks for dogear.  It's been a big help while waiting for a proper APM solution for our stuff.
